var express = require("express");
var app = express();
var client = express();
var http = require("http").Server(http);
var io = require('socket.io')(http);
var port = process.env.PORT || 5000;

// Serve client side app from the /dist folder generated by gulp
client.all('/', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "X-Requested-With");
  next();
 });
client.use(express.static(__dirname + '/dist'));
client.listen(3000);

// Server side app uses port 5000. Always.
app.use(express.static(__dirname + "/"));
http.listen(port, function(){
  console.log('listening on *:' +  port);
});

var playlist = [],
    start;
// use like this:
io.on('connection', function(socket) {
    console.log('connected to io');
    if (playlist.length) {
        console.log('sending first song', playlist[0]);
        socket.emit('playSong', playlist[0], (new Date()).getTime() - start);
    }
	socket.on('newtrack', function(track) {
		playlist.push(track);
        console.log('added track', playlist);
        if (playlist.length === 1) playNextSong(true);
        socket.broadcast.emit('playlistUpdate', playlist);
	});

    socket.on('reset', function() {
        playlist = [];
    });

    socket.on('getPlaylist', function() {
        socket.emit('playlist', playlist);
    });
});

function playNextSong(isFirst) {
    if (!isFirst) playlist.shift();
    if (playlist.length === 0) {
        io.sockets.emit('noMore');
        return;
    }
    console.log('playing next song', playlist);
    io.sockets.emit('playSong', playlist[0], 0);
    start = (new Date()).getTime();
    setTimeout(playNextSong, playlist[0].duration + 10);
}
